-- create tablespace and user

-- @ by oracle

DROP TABLESPACE DBTEST INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DBTEST_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP USER U_CT CASCADE;

CREATE TABLESPACE DBTEST LOGGING DATAFILE 'c:/data/DBTEST/MAIN.dbf' SIZE 500M AUTOEXTEND ON NEXT 200M MAXSIZE 2048M;
CREATE TEMPORARY TABLESPACE DBTEST_TEMP TEMPFILE 'c:/data/DBTEST/TEMP.dbf' SIZE 100M AUTOEXTEND ON NEXT 32M MAXSIZE 500M;
CREATE USER U_CT IDENTIFIED BY ORCL DEFAULT TABLESPACE DBTEST TEMPORARY TABLESPACE DBTEST_TEMP;
GRANT CONNECT,RESOURCE TO U_CT;