DROP TABLESPACE DBCASETOTAL INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE DBCASETOTAL_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP USER U_CT CASCADE;

CREATE TABLESPACE DBCASETOTAL LOGGING DATAFILE 'c:/data/DBCASETOTAL/MAIN.dbf' SIZE 500M AUTOEXTEND ON NEXT 200M MAXSIZE 2048M;
CREATE TEMPORARY TABLESPACE DBCASETOTAL_TEMP TEMPFILE 'c:/data/DBCASETOTAL/TEMP.dbf' SIZE 100M AUTOEXTEND ON NEXT 32M MAXSIZE 500M;
CREATE USER U_CT IDENTIFIED BY ORCL DEFAULT TABLESPACE DBCASETOTAL TEMPORARY TABLESPACE DBCASETOTAL_TEMP;
GRANT CONNECT,RESOURCE TO U_CT;